// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"signIn/ent/migrate"

	"signIn/ent/polls"
	"signIn/ent/user"
	"signIn/ent/votes"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Polls is the client for interacting with the Polls builders.
	Polls *PollsClient
	// User is the client for interacting with the User builders.
	User *UserClient
	// Votes is the client for interacting with the Votes builders.
	Votes *VotesClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Polls = NewPollsClient(c.config)
	c.User = NewUserClient(c.config)
	c.Votes = NewVotesClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:    ctx,
		config: cfg,
		Polls:  NewPollsClient(cfg),
		User:   NewUserClient(cfg),
		Votes:  NewVotesClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:    ctx,
		config: cfg,
		Polls:  NewPollsClient(cfg),
		User:   NewUserClient(cfg),
		Votes:  NewVotesClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Polls.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Polls.Use(hooks...)
	c.User.Use(hooks...)
	c.Votes.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Polls.Intercept(interceptors...)
	c.User.Intercept(interceptors...)
	c.Votes.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *PollsMutation:
		return c.Polls.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	case *VotesMutation:
		return c.Votes.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// PollsClient is a client for the Polls schema.
type PollsClient struct {
	config
}

// NewPollsClient returns a client for the Polls from the given config.
func NewPollsClient(c config) *PollsClient {
	return &PollsClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `polls.Hooks(f(g(h())))`.
func (c *PollsClient) Use(hooks ...Hook) {
	c.hooks.Polls = append(c.hooks.Polls, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `polls.Intercept(f(g(h())))`.
func (c *PollsClient) Intercept(interceptors ...Interceptor) {
	c.inters.Polls = append(c.inters.Polls, interceptors...)
}

// Create returns a builder for creating a Polls entity.
func (c *PollsClient) Create() *PollsCreate {
	mutation := newPollsMutation(c.config, OpCreate)
	return &PollsCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Polls entities.
func (c *PollsClient) CreateBulk(builders ...*PollsCreate) *PollsCreateBulk {
	return &PollsCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PollsClient) MapCreateBulk(slice any, setFunc func(*PollsCreate, int)) *PollsCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PollsCreateBulk{err: fmt.Errorf("calling to PollsClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PollsCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PollsCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Polls.
func (c *PollsClient) Update() *PollsUpdate {
	mutation := newPollsMutation(c.config, OpUpdate)
	return &PollsUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PollsClient) UpdateOne(_m *Polls) *PollsUpdateOne {
	mutation := newPollsMutation(c.config, OpUpdateOne, withPolls(_m))
	return &PollsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PollsClient) UpdateOneID(id int) *PollsUpdateOne {
	mutation := newPollsMutation(c.config, OpUpdateOne, withPollsID(id))
	return &PollsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Polls.
func (c *PollsClient) Delete() *PollsDelete {
	mutation := newPollsMutation(c.config, OpDelete)
	return &PollsDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PollsClient) DeleteOne(_m *Polls) *PollsDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PollsClient) DeleteOneID(id int) *PollsDeleteOne {
	builder := c.Delete().Where(polls.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PollsDeleteOne{builder}
}

// Query returns a query builder for Polls.
func (c *PollsClient) Query() *PollsQuery {
	return &PollsQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePolls},
		inters: c.Interceptors(),
	}
}

// Get returns a Polls entity by its id.
func (c *PollsClient) Get(ctx context.Context, id int) (*Polls, error) {
	return c.Query().Where(polls.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PollsClient) GetX(ctx context.Context, id int) *Polls {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *PollsClient) Hooks() []Hook {
	return c.hooks.Polls
}

// Interceptors returns the client interceptors.
func (c *PollsClient) Interceptors() []Interceptor {
	return c.inters.Polls
}

func (c *PollsClient) mutate(ctx context.Context, m *PollsMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PollsCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PollsUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PollsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PollsDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Polls mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(_m *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(_m))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id int) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(_m *User) *UserDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id int) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id int) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id int) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// VotesClient is a client for the Votes schema.
type VotesClient struct {
	config
}

// NewVotesClient returns a client for the Votes from the given config.
func NewVotesClient(c config) *VotesClient {
	return &VotesClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `votes.Hooks(f(g(h())))`.
func (c *VotesClient) Use(hooks ...Hook) {
	c.hooks.Votes = append(c.hooks.Votes, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `votes.Intercept(f(g(h())))`.
func (c *VotesClient) Intercept(interceptors ...Interceptor) {
	c.inters.Votes = append(c.inters.Votes, interceptors...)
}

// Create returns a builder for creating a Votes entity.
func (c *VotesClient) Create() *VotesCreate {
	mutation := newVotesMutation(c.config, OpCreate)
	return &VotesCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Votes entities.
func (c *VotesClient) CreateBulk(builders ...*VotesCreate) *VotesCreateBulk {
	return &VotesCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *VotesClient) MapCreateBulk(slice any, setFunc func(*VotesCreate, int)) *VotesCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &VotesCreateBulk{err: fmt.Errorf("calling to VotesClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*VotesCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &VotesCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Votes.
func (c *VotesClient) Update() *VotesUpdate {
	mutation := newVotesMutation(c.config, OpUpdate)
	return &VotesUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *VotesClient) UpdateOne(_m *Votes) *VotesUpdateOne {
	mutation := newVotesMutation(c.config, OpUpdateOne, withVotes(_m))
	return &VotesUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *VotesClient) UpdateOneID(id int) *VotesUpdateOne {
	mutation := newVotesMutation(c.config, OpUpdateOne, withVotesID(id))
	return &VotesUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Votes.
func (c *VotesClient) Delete() *VotesDelete {
	mutation := newVotesMutation(c.config, OpDelete)
	return &VotesDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *VotesClient) DeleteOne(_m *Votes) *VotesDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *VotesClient) DeleteOneID(id int) *VotesDeleteOne {
	builder := c.Delete().Where(votes.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &VotesDeleteOne{builder}
}

// Query returns a query builder for Votes.
func (c *VotesClient) Query() *VotesQuery {
	return &VotesQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeVotes},
		inters: c.Interceptors(),
	}
}

// Get returns a Votes entity by its id.
func (c *VotesClient) Get(ctx context.Context, id int) (*Votes, error) {
	return c.Query().Where(votes.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *VotesClient) GetX(ctx context.Context, id int) *Votes {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *VotesClient) Hooks() []Hook {
	return c.hooks.Votes
}

// Interceptors returns the client interceptors.
func (c *VotesClient) Interceptors() []Interceptor {
	return c.inters.Votes
}

func (c *VotesClient) mutate(ctx context.Context, m *VotesMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&VotesCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&VotesUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&VotesUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&VotesDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Votes mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Polls, User, Votes []ent.Hook
	}
	inters struct {
		Polls, User, Votes []ent.Interceptor
	}
)
