// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"signIn/ent/polls"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PollsCreate is the builder for creating a Polls entity.
type PollsCreate struct {
	config
	mutation *PollsMutation
	hooks    []Hook
}

// SetTitle sets the "Title" field.
func (_c *PollsCreate) SetTitle(v string) *PollsCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetOptions sets the "Options" field.
func (_c *PollsCreate) SetOptions(v []string) *PollsCreate {
	_c.mutation.SetOptions(v)
	return _c
}

// SetCreatedAt sets the "CreatedAt" field.
func (_c *PollsCreate) SetCreatedAt(v time.Time) *PollsCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetCreatedBy sets the "CreatedBy" field.
func (_c *PollsCreate) SetCreatedBy(v string) *PollsCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// Mutation returns the PollsMutation object of the builder.
func (_c *PollsCreate) Mutation() *PollsMutation {
	return _c.mutation
}

// Save creates the Polls in the database.
func (_c *PollsCreate) Save(ctx context.Context) (*Polls, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PollsCreate) SaveX(ctx context.Context) *Polls {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PollsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PollsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PollsCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "Title", err: errors.New(`ent: missing required field "Polls.Title"`)}
	}
	if _, ok := _c.mutation.Options(); !ok {
		return &ValidationError{Name: "Options", err: errors.New(`ent: missing required field "Polls.Options"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "CreatedAt", err: errors.New(`ent: missing required field "Polls.CreatedAt"`)}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "CreatedBy", err: errors.New(`ent: missing required field "Polls.CreatedBy"`)}
	}
	return nil
}

func (_c *PollsCreate) sqlSave(ctx context.Context) (*Polls, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PollsCreate) createSpec() (*Polls, *sqlgraph.CreateSpec) {
	var (
		_node = &Polls{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(polls.Table, sqlgraph.NewFieldSpec(polls.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(polls.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Options(); ok {
		_spec.SetField(polls.FieldOptions, field.TypeJSON, value)
		_node.Options = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(polls.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(polls.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	return _node, _spec
}

// PollsCreateBulk is the builder for creating many Polls entities in bulk.
type PollsCreateBulk struct {
	config
	err      error
	builders []*PollsCreate
}

// Save creates the Polls entities in the database.
func (_c *PollsCreateBulk) Save(ctx context.Context) ([]*Polls, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Polls, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PollsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PollsCreateBulk) SaveX(ctx context.Context) []*Polls {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PollsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PollsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
