// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"signIn/ent/polls"
	"signIn/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// PollsUpdate is the builder for updating Polls entities.
type PollsUpdate struct {
	config
	hooks    []Hook
	mutation *PollsMutation
}

// Where appends a list predicates to the PollsUpdate builder.
func (_u *PollsUpdate) Where(ps ...predicate.Polls) *PollsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "Title" field.
func (_u *PollsUpdate) SetTitle(v string) *PollsUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "Title" field if the given value is not nil.
func (_u *PollsUpdate) SetNillableTitle(v *string) *PollsUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetOptions sets the "Options" field.
func (_u *PollsUpdate) SetOptions(v []string) *PollsUpdate {
	_u.mutation.SetOptions(v)
	return _u
}

// AppendOptions appends value to the "Options" field.
func (_u *PollsUpdate) AppendOptions(v []string) *PollsUpdate {
	_u.mutation.AppendOptions(v)
	return _u
}

// SetCreatedAt sets the "CreatedAt" field.
func (_u *PollsUpdate) SetCreatedAt(v time.Time) *PollsUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "CreatedAt" field if the given value is not nil.
func (_u *PollsUpdate) SetNillableCreatedAt(v *time.Time) *PollsUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetCreatedBy sets the "CreatedBy" field.
func (_u *PollsUpdate) SetCreatedBy(v string) *PollsUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "CreatedBy" field if the given value is not nil.
func (_u *PollsUpdate) SetNillableCreatedBy(v *string) *PollsUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// Mutation returns the PollsMutation object of the builder.
func (_u *PollsUpdate) Mutation() *PollsMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PollsUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PollsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PollsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PollsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PollsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(polls.Table, polls.Columns, sqlgraph.NewFieldSpec(polls.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(polls.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Options(); ok {
		_spec.SetField(polls.FieldOptions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedOptions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, polls.FieldOptions, value)
		})
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(polls.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(polls.FieldCreatedBy, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{polls.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PollsUpdateOne is the builder for updating a single Polls entity.
type PollsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PollsMutation
}

// SetTitle sets the "Title" field.
func (_u *PollsUpdateOne) SetTitle(v string) *PollsUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "Title" field if the given value is not nil.
func (_u *PollsUpdateOne) SetNillableTitle(v *string) *PollsUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetOptions sets the "Options" field.
func (_u *PollsUpdateOne) SetOptions(v []string) *PollsUpdateOne {
	_u.mutation.SetOptions(v)
	return _u
}

// AppendOptions appends value to the "Options" field.
func (_u *PollsUpdateOne) AppendOptions(v []string) *PollsUpdateOne {
	_u.mutation.AppendOptions(v)
	return _u
}

// SetCreatedAt sets the "CreatedAt" field.
func (_u *PollsUpdateOne) SetCreatedAt(v time.Time) *PollsUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "CreatedAt" field if the given value is not nil.
func (_u *PollsUpdateOne) SetNillableCreatedAt(v *time.Time) *PollsUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetCreatedBy sets the "CreatedBy" field.
func (_u *PollsUpdateOne) SetCreatedBy(v string) *PollsUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "CreatedBy" field if the given value is not nil.
func (_u *PollsUpdateOne) SetNillableCreatedBy(v *string) *PollsUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// Mutation returns the PollsMutation object of the builder.
func (_u *PollsUpdateOne) Mutation() *PollsMutation {
	return _u.mutation
}

// Where appends a list predicates to the PollsUpdate builder.
func (_u *PollsUpdateOne) Where(ps ...predicate.Polls) *PollsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PollsUpdateOne) Select(field string, fields ...string) *PollsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Polls entity.
func (_u *PollsUpdateOne) Save(ctx context.Context) (*Polls, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PollsUpdateOne) SaveX(ctx context.Context) *Polls {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PollsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PollsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PollsUpdateOne) sqlSave(ctx context.Context) (_node *Polls, err error) {
	_spec := sqlgraph.NewUpdateSpec(polls.Table, polls.Columns, sqlgraph.NewFieldSpec(polls.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Polls.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, polls.FieldID)
		for _, f := range fields {
			if !polls.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != polls.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(polls.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Options(); ok {
		_spec.SetField(polls.FieldOptions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedOptions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, polls.FieldOptions, value)
		})
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(polls.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(polls.FieldCreatedBy, field.TypeString, value)
	}
	_node = &Polls{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{polls.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
