// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"signIn/ent/predicate"
	"signIn/ent/votes"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// VotesUpdate is the builder for updating Votes entities.
type VotesUpdate struct {
	config
	hooks    []Hook
	mutation *VotesMutation
}

// Where appends a list predicates to the VotesUpdate builder.
func (_u *VotesUpdate) Where(ps ...predicate.Votes) *VotesUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPollID sets the "PollID" field.
func (_u *VotesUpdate) SetPollID(v int) *VotesUpdate {
	_u.mutation.ResetPollID()
	_u.mutation.SetPollID(v)
	return _u
}

// SetNillablePollID sets the "PollID" field if the given value is not nil.
func (_u *VotesUpdate) SetNillablePollID(v *int) *VotesUpdate {
	if v != nil {
		_u.SetPollID(*v)
	}
	return _u
}

// AddPollID adds value to the "PollID" field.
func (_u *VotesUpdate) AddPollID(v int) *VotesUpdate {
	_u.mutation.AddPollID(v)
	return _u
}

// SetVotes sets the "Votes" field.
func (_u *VotesUpdate) SetVotes(v map[string][]string) *VotesUpdate {
	_u.mutation.SetVotes(v)
	return _u
}

// Mutation returns the VotesMutation object of the builder.
func (_u *VotesUpdate) Mutation() *VotesMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *VotesUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VotesUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *VotesUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VotesUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *VotesUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(votes.Table, votes.Columns, sqlgraph.NewFieldSpec(votes.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PollID(); ok {
		_spec.SetField(votes.FieldPollID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPollID(); ok {
		_spec.AddField(votes.FieldPollID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Votes(); ok {
		_spec.SetField(votes.FieldVotes, field.TypeJSON, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{votes.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// VotesUpdateOne is the builder for updating a single Votes entity.
type VotesUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *VotesMutation
}

// SetPollID sets the "PollID" field.
func (_u *VotesUpdateOne) SetPollID(v int) *VotesUpdateOne {
	_u.mutation.ResetPollID()
	_u.mutation.SetPollID(v)
	return _u
}

// SetNillablePollID sets the "PollID" field if the given value is not nil.
func (_u *VotesUpdateOne) SetNillablePollID(v *int) *VotesUpdateOne {
	if v != nil {
		_u.SetPollID(*v)
	}
	return _u
}

// AddPollID adds value to the "PollID" field.
func (_u *VotesUpdateOne) AddPollID(v int) *VotesUpdateOne {
	_u.mutation.AddPollID(v)
	return _u
}

// SetVotes sets the "Votes" field.
func (_u *VotesUpdateOne) SetVotes(v map[string][]string) *VotesUpdateOne {
	_u.mutation.SetVotes(v)
	return _u
}

// Mutation returns the VotesMutation object of the builder.
func (_u *VotesUpdateOne) Mutation() *VotesMutation {
	return _u.mutation
}

// Where appends a list predicates to the VotesUpdate builder.
func (_u *VotesUpdateOne) Where(ps ...predicate.Votes) *VotesUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *VotesUpdateOne) Select(field string, fields ...string) *VotesUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Votes entity.
func (_u *VotesUpdateOne) Save(ctx context.Context) (*Votes, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VotesUpdateOne) SaveX(ctx context.Context) *Votes {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *VotesUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VotesUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *VotesUpdateOne) sqlSave(ctx context.Context) (_node *Votes, err error) {
	_spec := sqlgraph.NewUpdateSpec(votes.Table, votes.Columns, sqlgraph.NewFieldSpec(votes.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Votes.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, votes.FieldID)
		for _, f := range fields {
			if !votes.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != votes.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PollID(); ok {
		_spec.SetField(votes.FieldPollID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPollID(); ok {
		_spec.AddField(votes.FieldPollID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Votes(); ok {
		_spec.SetField(votes.FieldVotes, field.TypeJSON, value)
	}
	_node = &Votes{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{votes.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
