// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"signIn/ent/votes"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Votes is the model entity for the Votes schema.
type Votes struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// PollID holds the value of the "PollID" field.
	PollID int `json:"PollID,omitempty"`
	// Votes holds the value of the "Votes" field.
	Votes        map[string][]string `json:"Votes,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Votes) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case votes.FieldVotes:
			values[i] = new([]byte)
		case votes.FieldID, votes.FieldPollID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Votes fields.
func (_m *Votes) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case votes.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case votes.FieldPollID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field PollID", values[i])
			} else if value.Valid {
				_m.PollID = int(value.Int64)
			}
		case votes.FieldVotes:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field Votes", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Votes); err != nil {
					return fmt.Errorf("unmarshal field Votes: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Votes.
// This includes values selected through modifiers, order, etc.
func (_m *Votes) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Votes.
// Note that you need to call Votes.Unwrap() before calling this method if this Votes
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Votes) Update() *VotesUpdateOne {
	return NewVotesClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Votes entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Votes) Unwrap() *Votes {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Votes is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Votes) String() string {
	var builder strings.Builder
	builder.WriteString("Votes(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("PollID=")
	builder.WriteString(fmt.Sprintf("%v", _m.PollID))
	builder.WriteString(", ")
	builder.WriteString("Votes=")
	builder.WriteString(fmt.Sprintf("%v", _m.Votes))
	builder.WriteByte(')')
	return builder.String()
}

// VotesSlice is a parsable slice of Votes.
type VotesSlice []*Votes
