// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Polls is the predicate function for polls builders.
type Polls func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Votes is the predicate function for votes builders.
type Votes func(*sql.Selector)
