// Code generated by ent, DO NOT EDIT.

package votes

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the votes type in the database.
	Label = "votes"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPollID holds the string denoting the pollid field in the database.
	FieldPollID = "poll_id"
	// FieldVotes holds the string denoting the votes field in the database.
	FieldVotes = "votes"
	// Table holds the table name of the votes in the database.
	Table = "votes"
)

// Columns holds all SQL columns for votes fields.
var Columns = []string{
	FieldID,
	FieldPollID,
	FieldVotes,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Votes queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPollID orders the results by the PollID field.
func ByPollID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPollID, opts...).ToFunc()
}
